"""Canonical telemetry field names."""

SPEED_KMH = "speed_kmh"
LAT_G = "lat_g"
LONG_G = "long_g"
GPS_LATITUDE_DEG = "gps_latitude_deg"
GPS_LONGITUDE_DEG = "gps_longitude_deg"
GPS_HEADING_DEG = "gps_heading_deg"
YAW_RATE_DPS = "yaw_rate_dps"
STEERING_DEG = "steering_deg"
THROTTLE_PCT = "throttle_pct"
ACCELERATOR_PCT = "accelerator_pct"
BRAKE_PRESSURE_KPA = "brake_pressure_kpa"
BRAKE_POS_PCT = "brake_pos_pct"
ENGINE_RPM = "engine_rpm"
GEAR = "gear"
LAP_NUMBER = "lap_number"
ENGINE_OIL_PRESSURE_KPA = "engine_oil_pressure_kpa"
ENGINE_OIL_TEMP_C = "engine_oil_temp_c"
COOLANT_TEMP_C = "coolant_temp_c"
GEARBOX_TEMP_C = "gearbox_temp_c"
